apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
  namespace: consul-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
      annotations:
        # Required annotation in order to inject the envoy sidecar proxy:
        consul.hashicorp.com/connect-inject: "true"
        ## Comma separated list of Consul service tags:
        ## Needs to be one line and no spaces,
        ## but can split long lines with \ in YAML:
        consul.hashicorp.com/service-tags: "\
          traefik.enable=true,\
          traefik.http.routers.whoami.entrypoints=web,\
          traefik.http.routers.whoami.rule=Host(`ks3.minimalgap.com`)"
          # traefik.http.routers.whoami.tls=true,\
          # traefik.http.routers.whoami.tls.certresolver=autoresolver"
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: consul-system
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
  selector:
    app: whoami